@startuml
[Webots Adaptor] ..> [Adaptor REST Controller]
[Demo Adaptor] ..> [Adaptor REST Controller]
[Azure Adaptor] ..> [Adaptor REST Controller]
[Webots Simulation]
[Azure DT]
[Manager] --> [Service Registry] : Queries
[Manager] --> [Adaptor REST Controller] : Routes requests
[Adaptor REST Controller] --> [Service Registry] : Registers
[Webots Adaptor] --> [Webots Simulation] : Executes Operation
[Azure Adaptor] --> [Azure DT] : Executes Operation
[Manager] --> [Axis Converter] : Uses
[Client] --> [UI] : Uses
[UI] --> [Manager] : Sends requests

@enduml
